version: '3.7'

services:
  zcorenetwork/genkey:
    image: zcorenetwork/genkey
    build:
      context: . 
    command:
      node index.js ${PASSWORD} ${PRIVATEKEY}
    volumes:
      - ./generate:/usr/src/app/generate
