version: '3.7'

services:
  zcr-genkey:
    image: zcorenetwork/genkey:0.0.3
    build:
      context: . 
    command:
      node index.js ${PASSWORD} ${PRIVATEKEY}
    volumes:
      - ./generate:/usr/src/app/generate
